# Generated by Django 5.0.7 on 2024-08-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=25)),
                ('company', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='testimonial/')),
            ],
        ),
    ]
